object Versions {
    const val jwt = "4.4.0"
    const val kotlin = "2.0.20"
    const val ktor = "2.3.12"
    const val lettuce = "6.4.0.RELEASE"
    const val logback = "1.5.8"
    const val koin = "3.5.6"
    const val exposed = "0.54.0"
    const val openAi = "3.8.2"
    const val coroutinesCore = "1.8.1"
    const val dateTime = "0.6.1"
    const val postgresql = "42.7.4"
    const val hikari = "5.1.0"
    const val commonsText = "1.12.0"
}
